### ISSUE TITLE
[prefmonitor] - Template pref "dom.vr.puppet.enabled" can be removed

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/prefpicker#45]
All entries in the `review_on_close` field for pref "dom.vr.puppet.enabled" have been resolved.  This pref entry can be safely removed.

**Comment by tysmith** [comment]
@pyoor Is `https://bugzilla.mozilla.org/show_bug.cgi?id=1573528` the correct value for `review_on_close` for this pref? That BugID points to an assertion not a meta bug as I'd expect.

**Comment by pyoor** [comment]
No.  I assume this assertion was a blocker of the entire VR variant.  Now that it's closed, let's remove the review on close but keep the variant disabled in automation.  I'll open a PR.
